### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './data/Eurlex-4K/train_raw_texts.txt'

### ISSUE THREAD

**Issue by zzzmm1** [kongds/LightXML#1]
Thanks for your excellent work! 
I download EUR-Lex.tar but only find train.txt, train_labels.txt, train_texts.txt, test.txt ,test_labels.txt and test_texts.txt.
There is no Eurlex-4K/train_raw_texts.txt in tar file.
Could you please tell me where to find such file? Thanks!

**Comment by kongds** [comment]
Sorry for the inconvenience. Just rename train_texts.txt and test_texts.txt to train_raw_texts.txt and test_raw_texts.txt.  

I will fix it.
