### ISSUE TITLE
Question on dataset 

### ISSUE THREAD

**Issue by jil818** [kongds/LightXML#10]
Hi, I am new to XMC. After downloading all datasets, I noticed that the labels for both test and train sets are number or index. I am wondering if there is a file storing the exact text label corresponding to each label index.
Thank you so much.

**Comment by kongds** [comment]
XMC datasets are preprocessed,  you can see the detail information of each datasets in   http://manikvarma.org/downloads/XC/XMLRepository.html#provenance.  The original datasets may contain label text.

**Comment by jil818** [comment]
I understand that you preprocessed all the dataset. After I downloaded raw dataset AmazonCat-13K from http://manikvarma.org/downloads/XC/XMLRepository.html#provenance, I found that these is no label text only numbers in both train_labels.txt and test_labels.txt.

**Comment by kongds** [comment]
The dataset is not preprocessed by us.  
Did you download raw AmazonCat-13K? For AmazonCat-13K, the label text is in raw AmazonCat-13k dataset. 
![image](https://user-images.githubusercontent.com/19282154/127090732-a2bc26c8-84b2-4ea7-b931-e2b2bb45b944.png)
[Yf.txt](https://github.com/kongds/LightXML/files/6882476/Yf.txt)

**Comment by jil818** [comment]
Oh I am sorry, I guess I downloaded the wrong raw dataset. I downloaded the one you show me previously, and checked the trn.json, noticing that the target_ind are numbers. Do these numbers correspond to the index of the text label in Yf.txt?

**Comment by kongds** [comment]
It should correspond, but i am not sure. You better check again

**Comment by jil818** [comment]
I will do it. Thank you so much!
