### ISSUE TITLE
Remove `apex` from requirements

### ISSUE THREAD

**Issue by sadrasabouri** [kongds/LightXML#14]
The `apex==0.9.10dev` that you mentioned in the requirements.txt file is not a valid version of `apex` which you wanted to use.
I got bellow error when running your code
```
  File "/usr/local/lib/python3.7/dist-packages/apex/__init__.py", line 13, in <module>
    from pyramid.session import UnencryptedCookieSessionFactoryConfig
ImportError: cannot import name 'UnencryptedCookieSessionFactoryConfig' from 'pyramid.session' (unknown location)
```
According to [this](https://stackoverflow.com/questions/66610378/unencryptedcookiesessionfactoryconfig-error-when-importing-apex) discussion best way to solve this issue is to:
1. remove `apex==0.9.10dev` from requirements.txt
2. add bellow instructions in readme as a step of requirement installation
```
git clone https://github.com/NVIDIA/apex
cd apex
python setup.py install
```

**Comment by kongds** [comment]
Thank you for your advice.

I have updated in https://github.com/kongds/LightXML/commit/09af8a4d2d8b3af5620f73dc3550f5c0a9aac7c6

**Comment by sadrasabouri** [comment]
Thank you for your fast response.
I'm using your code on Google Colab and it seems that the `torch==1.5.1` is not compatible with the bellow command (not compatible **CUDA** version)
```
python setup.py install --cuda_ext --cpp_ext
```
I'll work on it and test other versions of torch and update this thread.

**Comment by kongds** [comment]
ok 
Maybe we can follow the quick start in https://github.com/NVIDIA/apex#linux.
