### ISSUE TITLE
Training about  Wiki10-31k

### ISSUE THREAD

**Issue by yc1999** [kongds/LightXML#15]
Thanks for your code !!!

After running your code, I found that you just did a simply binary classification for `Wiki10-31k` (without **label recalling** , **label ranking** and **dynamic negative sampling**) :

https://github.com/kongds/LightXML/blob/b9af9443004d3bce8b9116edfe038b702d1b295c/src/model.py#L100-L107

![image](https://user-images.githubusercontent.com/37548571/168463765-2459352d-3271-4019-af42-cf29f6f4720b.png)

So, I wonder whether it was all you've done for `Wiki10-31k` or I missed something important, thanks a lot!

**Comment by kongds** [comment]
Yes
Following [AttentionXML](https://github.com/yourh/AttentionXML), LightXML only uses label clustering in Wiki500K and Amazon670K.  
For remain datasets, we directly use multi layers text representation with BCE.

**Comment by yc1999** [comment]
> Yes Following [AttentionXML](https://github.com/yourh/AttentionXML), LightXML only uses label clustering in Wiki500K and Amazon670K. For remain datasets, we directly use multi layers text representation with BCE.

okay, thanks! 
If it is just a simple BCE,  the improvement of LightXML on `Wiki10-31k` against AttentionXML may derive from t**he multi layers text representation** ?

**Comment by kongds** [comment]
AttentionXML uses BiLSTM, while LightXML uses BERT.
The improvement is not only multi layers text representation, but also different text encoders.
