### ISSUE TITLE
version of Python&Bert pretrained model

### ISSUE THREAD

**Issue by wangchichi1999** [kongds/LightXML#2]
Hi! Great work! 
: D
If the version of Python is 3.6 in your code?
And
Does LightXML just use Bert-base-uncased from Huggingface, or train it on specific corpus for specific task？
Thanks!

**Comment by kongds** [comment]
Thank you.

1. The python version we use is 3.8.3.

2. We just use BERT from hugginface.

**Comment by wangchichi1999** [comment]
Got it!
Thanks!
