### ISSUE TITLE
How could I generate the predictions?

### ISSUE THREAD

**Issue by celsofranssa** [kongds/LightXML#20]
The training step produces these 3 model checkpoints:

- model-Eurlex-4k.bin (10:12)
- model-Eurlex-4k_roberta.bin (11:26)
- model-Eurlex-4k_xlnet.bin (16:20)

How can I generate the predictions for the test split(`labels.npy` and `scores.npy`)?

**Comment by kongds** [comment]
For small datasets like Eurex 4k, you can save all label scores by add following line after `src/ensemble.py line37`:
```python
        np.save(f'results/{model_name}-labels.npy', predicts[-1].cpu().numpy())
```

**Comment by celsofranssa** [comment]
> For small datasets like Eurex 4k, you can save all label scores by add following line after `src/ensemble.py line37`:
> 
> ```python
>         np.save(f'results/{model_name}-labels.npy', predicts[-1].cpu().numpy())
> ```

Note that [src/ensemble.py line37](https://github.com/kongds/LightXML/blob/b9af9443004d3bce8b9116edfe038b702d1b295c/src/ensemble.py#L22) is inside the for loop:
https://github.com/kongds/LightXML/blob/b9af9443004d3bce8b9116edfe038b702d1b295c/src/ensemble.py#L22-L38 

Therefore, I think that in small datasets such as `Eurlex-4k`, which use at least RoBERTa, and XLNET in the ensemble, inserting the code snippet you suggested inside the loop, both the labels and the scores will be overwritten by the last model. 

Or did I miss something?

**Comment by kongds** [comment]
The last model will not override it and `model_name` is used to identify predictions.  It will save three predictions of bert, robera and xlnet separately.

**Comment by celsofranssa** [comment]
I see. Then,
    (i) to evaluate, should I open these three files and only add the correspondent scores?
    (ii) am I correct in assuming that the predicted label is the index of the scores vector?

**Comment by kongds** [comment]
1. to evaluate them just by loading them to `predictions`: https://github.com/kongds/LightXML/blob/b9af9443004d3bce8b9116edfe038b702d1b295c/src/ensemble.py#L39-L65

2. Yes, the index of the scores vector is label

**Comment by celsofranssa** [comment]
In the evaluating step, I'd like to include metrics besides accuracy and precision (such as the commonly used Propensity Scored Precision - PSP@k). So I want to ensure that the final score for each label is the sum of each model's predictions.

**Comment by kongds** [comment]
The final score is sum the sigmoid label score.  You need to use sigmoid before sum it.

**Comment by celsofranssa** [comment]
By the way, what adaptations should I implement in large datasets such as Amazon-670k to save the predictions?

**Comment by kongds** [comment]
We have saved predictions for large datasets `labels.npy` and `scores.npy`.

**Comment by celsofranssa** [comment]
Thank you for all your help.
