### ISSUE TITLE
How to generate labels group?

### ISSUE THREAD

**Issue by celsofranssa** [kongds/LightXML#21]
The script to run LightXML in Amazon-670k dataset start with: 
https://github.com/kongds/LightXML/blob/b9af9443004d3bce8b9116edfe038b702d1b295c/run.sh#L24-L54

to download the label group.

Since my research requires experiments with different train-test splits (k-fold cross-validation),  it requires generating these label groups for each fold. 

If this is right, could you give the directions to generate these groups?

**Comment by kongds** [comment]
You can cluster with following 
https://github.com/kongds/LightXML/blob/b9af9443004d3bce8b9116edfe038b702d1b295c/run.sh#L34

**Comment by celsofranssa** [comment]
Whit some adaptations, it is running.
