### ISSUE TITLE
issue of dataset Amazon670k

### ISSUE THREAD

**Issue by huiyegit** [kongds/LightXML#7]
The program has the error below. Is the running command correct in the file 'run.sh' for dataset Amazon670K?

![image](https://user-images.githubusercontent.com/31486250/118377469-5ffe6d00-b59b-11eb-987e-e6b42a7d5dbb.png)

**Comment by kongds** [comment]
Sorry, I have fixed it in here https://github.com/kongds/LightXML/commit/c7fd941bb4f75a21bd94173bb142277e15a98bec .
